---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.controller
  - name: infra.controller_configuration
  - name: infra.ah_configuration
  - name: infra.ee_utilities
  - name: infra.aap_utilities
