ancestor: null
releases:
  0.1.0-devel:
    release_date: '2023-08-17'
  1.0.0:
    changes:
      bugfixes:
      - Fixed error message when project sync fails
      - fixed a bug where resolve_name_to_id data was not defined
      - fixed a bug with the API returning multiple items because it only matches
        the name starting with the value
      major_changes:
      - Add dispatch role
      - Added credential module
      - Added credential role
      - Added decision environment module
      - Added decision environment role
      - Added project module
      - Added project role
      - Added project_sync module
      - Added project_sync role
      - Added rulebook_activation module
      - Added rulebook_activation role
      - Added user module
      - Added user role
      - Added user_token module
      - Added user_token role
    fragments:
    - activations.yml
    - bugfix.yml
    - credential.yml
    - decision_environment.yml
    - dispatch.yml
    - project.yml
    - user.yml
    - user_token.yml
    release_date: '2024-04-08'
