---
controller_projects:
- name: aap.dailydemo.F5
  organization: "{{ my_organization }}"
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ericcames/aap.dailydemo.F5.git
  wait: true