---
gateway_settings:
  gateway_token_name: X-DAB-JW-TOKEN
  gateway_access_token_expiration: 600
  gateway_basic_auth_enabled: true
  gateway_proxy_url: https://socrates.internal.ames.net
  gateway_proxy_url_ignore_cert: true
  password_min_length: 0
  password_min_digits: 0
  password_min_upper: 0
  password_min_special: 0
  allow_admins_to_set_insecure: false
  custom_login_info: |-
    THIS SYSTEM IS PROVIDED FOR USE BY AUTHORIZED USERS ONLY.
    ALERT! You are entering into a secured area! Your IP, Login Time, Username
    has been noted and has been sent to the server administrator! All activities
    on this system are logged. Unauthorized access will be fully investigated and
    reported to the appropriate law enforcement agencies.
  # custom_logo: ./files/my_logo.png
