download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-eda_configuration-1.1.0.tar.gz
format_version: 1.0.0
name: eda_configuration
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/infra/eda_configuration/versions/1.1.0/
