---
ansible-navigator:
  ansible:
    config:
      path: ./ansible.cfg
  execution-environment:
    image: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8
    pull:
      policy: missing
  playbook-artifact:
    enable: false
