---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
      manifest_file_name: manifest_Zigfreed_20240528T153016Z.zip
  vars_files:
    - files/{{ manifest_file_name }}

  tasks:

    - name: Print
      ansible.builtin.debug:
        msg: "hello"
