---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    my_manifest_file: manifest_Zigfreed_20240528T153016Z.zip
    controller_validate_certs: false
    controller_hostname: controller.example.com
    controller_username: admin
    controller_password: changeme
    controller_license:
      manifest_file: files/manifest_Zigfreed_20240528T153016Z.zip

  roles:
    - {role: infra.controller_configuration.license}
