---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    manifest_file_name: manifest_Zigfreed_20240528T153016Z.zip
  vars_files:
    - playbooks/files/"{{ manifest_file_name }}"

  pre_tasks:
    - name: Check for our mandatory variables
      # You can create a custom credential for the mandatory variables
      ansible.builtin.assert:
        that:
          - controller_hostname is defined
          - controller_username is defined
          - controller_password is defined
        fail_msg: |
          Define following vars here, or in controller_configs/controller_auth.yml
          controller_hostname: ansible-controller-web-svc-test-project.example.com
          controller_username: admin
          controller_password: changeme
        success_msg: "All mandatory variables have been set"

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./yaml
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  # roles:
  #   - {role: infra.controller_configuration.license, when: controller_license is defined}